# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: tchiak
      POSTGRES_DB: default
    ports:
      - 1234:5432
    volumes:
      - "/Users/acschw2/Desktop/develop/docker/var/lib/postgresql/data:/var/lib/postgresql/data"
  app:
    image: rest-api
    restart: always
    ports:
      - 8000:8000